### ISSUE TITLE
Compile error when go getting

### ISSUE THREAD

**Issue by tpdenk** [fgrosse/go-home#1] opened 2019-06-02 18:20 UTC
```
$ go get github.com/fgrosse/go-home
# github.com/fgrosse/go-home
../go/src/github.com/fgrosse/go-home/app.go:80:3: unknown field 'AlwaysOnTop' in struct literal of type pixelgl.WindowConfig
```

**Comment by fgrosse** [comment] 2019-06-03 09:20
You probably tried either with an old Go version or inside the `$GOPATH` where go modules are still disabled?

The pixel dependency [should currently be pulled in from a branch of my fork][1] (`github.com/fgrosse/pixel`) because I am waiting for faiface/pixel#186 to be merged.

If you have Go 1.11 or higher you should be able to work around this via

```
GO111MODULE=on go get github.com/fgrosse/go-home
```

Alternatively you can clone this repo outside your GOPATH, cd into it and then do `go install`. Note that you need to install the required external dependencies for OpenGL (see README.md)

[1]: https://github.com/fgrosse/go-home/blob/28f98a03c0054eed97771d048d36a5a067d51d0d/go.mod#L17

**Comment by tpdenk** [comment] 2019-06-03 14:56
```
GOARCH="amd64"
GOBIN=""
GOCACHE="~/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="~/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/44/txz_wqq568n4lbh6014ft754hlbqxb/T/go-build351885161=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

OpenGL is installed, I tried both outside a project and inside a project, both inside and outside of my GOPATH.

It is a compile-error, so I don't think it has anything to do with my OpenGL installation.

**Comment by tpdenk** [comment] 2019-06-03 14:58
Cloning and installing it works.
You should prob still look into this compile error.

**Comment by fgrosse** [comment] 2019-06-03 17:13
It's interesting and I will try and reproduce the issue on a fresh checkout. Maybe it's really a problem with the `replace` directive when using `go get` with modules?

Thanks for reporting and the extra info :)

**Closed as completed** 2019-06-16 11:20 UTC

**Comment by fgrosse** [comment] 2019-06-16 11:21
I decided to document installation better. Using `go get` for an application (i.e. not a library) isn't really useful. Thanks again for drawing my attention to this :)
